@default_files=('D4.5.tex');
push @generated_exts, 'acn', 'acr', 'alg', 'glg', 'glo', 'gls', 'glsdefs', 'slg', 'slo', 'sls', 'ist', 'run.xml', 'fdb_latexmk';
$cleanup_includes_generated = 1;
$clean_full_ext .= " %R-blx.bib bbl %R.run.xml %R.fdb_latexmk";
